#include "klibtest.h"
#include <limits.h>

long long testset[] = {0, INT_MAX / 17, INT_MAX, INT_MIN, INT_MIN + 1,
              UINT_MAX / 17, INT_MAX / 17, UINT_MAX};
char * ans[] = {"Number: 0","Number: 126322567","Number: 2147483647",
        "Number: -2147483648","Number: -2147483647","Number: 252645135",
        "Number: 126322567","Number: -1"};

void test_sprintf() {
    for(int i = 0;i<8;i++) {
        sprintf(dest, "Number: %d",(int)testset[i]);
        assert(strcmp(dest, ans[i]) == 0);
    }

    /*generated by GPT*/
    const char *str1 = "Hello";
    sprintf(dest, "String: %s", str1);
    assert(strcmp(dest, "String: Hello") == 0);

    const char *str2 = "";
    sprintf(dest, "String: %s", str2);
    assert(strcmp(dest, "String: ") == 0);

    const char *str3 = "This is a longer string for testing.";
    sprintf(dest, "String: %s", str3);
    assert(strcmp(dest, "String: This is a longer string for testing.") == 0);

    sprintf(dest, "%.3s", str1);
    assert(strcmp(dest, "Hel") == 0);

    sprintf(dest, "%5d", 42);
    assert(strcmp(dest, "   42") == 0);

    sprintf(dest, "%05d", 42);
    assert(strcmp(dest, "00042") == 0); 

    sprintf(dest, "% d", 42);
    assert(strcmp(dest, " 42") == 0); 

    sprintf(dest, "%+d", 42);
    assert(strcmp(dest, "+42") == 0);

    sprintf(dest, "%x", 42);
    assert(strcmp(dest, "2a") == 0);

    sprintf(dest, "%#08x", 42);
    assert(strcmp(dest, "0x00002a") == 0);

    sprintf(dest, "%#8x", 42);
    assert(strcmp(dest, "    0x2a") == 0);

    int num = 10;
    sprintf(dest, "%p", (void*)&num);
    assert(strcmp(dest, "0xa") == 0);
}


int main() {
    test_sprintf();
    return 0;
}