#include "klibtest.h"

/*generated by GPT*/
void test_strcpy() {
    const char *src1 = "Hello, World!";
    strcpy(dest, src1);
    check(strcmp(dest, src1) == 0);

    const char *src2 = "";
    strcpy(dest, src2);
    check(strcmp(dest, src2) == 0);

    const char *src3 = "This is a longer string that we are going to copy.";
    strcpy(dest, src3);
    check(strcmp(dest, src3) == 0);
}


int main() {
  test_strcpy();
  return 0;
}