#include "klibtest.h"

/*generated by GPT*/
void test_strlen() {
  const char *str1 = "Hello";
    assert(strlen(str1) == 5);

    const char *str2 = "";
    assert(strlen(str2) == 0);

    const char *str3 = "Hello, World!";
    assert(strlen(str3) == 13);

    const char *str4 = "   Leading and trailing spaces   ";
    assert(strlen(str4) == 33);

    const char *str5 = "こんにちは";
    // "こんにちは" is 5 characters long in UTF-8, but each character is more than one byte
    assert(strlen(str5) == 15); // In UTF-8 each character takes 3 bytes, so 5*3=15

    const char *str6 = "Hello, 世界";
    // "Hello, 世界" is 13 characters long where "世界" takes 6 bytes
    assert(strlen(str6) == 13);
}

int main() {
  test_strlen();
  return 0;
}