#include "klibtest.h"

/*generated by GPT*/
void test_strncpy() {
    const char *src1 = "Hello";
    strncpy(dest, src1, sizeof(dest));
    assert(strcmp(dest, src1) == 0);

    const char *src2 = "Hello, World!";
    strncpy(dest, src2, strlen(src2) + 1); // +1 for null terminator
    assert(strcmp(dest, src2) == 0);

    const char *src3 = "This string is too long";
    strncpy(dest, src3, 10);
    dest[10] = '\0'; // Ensure null termination
    assert(strncmp(dest, src3, 10) == 0);

    const char *src4 = "";
    strncpy(dest, src4, sizeof(dest));
    assert(strcmp(dest, src4) == 0);

    const char *src5 = "Short";
    strncpy(dest, src5, sizeof(dest));
    assert(strcmp(dest, src5) == 0);
    // Check if the rest of the buffer is filled with null characters
    for (size_t i = strlen(src5) + 1; i < sizeof(dest); ++i) {
        assert(dest[i] == '\0');
    }
}

int main() {
  test_strncpy();
  return 0;
}